### PR TITLE
Added size check for Tuple equal and equivalence

### PR DESCRIPTION
**Pull request by c-schuler**
This is a fix for issue #63

### CODE REVIEW

**Comment by c-schuler** [comment]
Well, they would have evaluated to true not false as I have the tests now. Although two more tests will be somewhat pointless as they will be testing the same thing (Tuples with different sizes return false), I will add the tests.

**Comment by duncand** [comment]
Its not pointless to add the tests.  The most important characteristic of added tests when fixing a bug is that the tests fail prior to the bug being fixed and pass after the bug is fixed.  Those kind of tests are the whole point of adding tests, demonstrating the bug actually fixed something.  This is what I was requesting.  "the bug is [specifically] that when the right-hand argument has any attributes that the left-hand attribute does not, this evades detection, and so non-equal Tuple could be called equal"  Additional tests that passed before the bug is fixed and continue to pass are also valuable, this being the kind of the 2 you had, but are secondary to the first kind.  Thank you.

**Comment by duncand** [comment]
Also, you need to add the XML versions of the tests.  Sorry I forgot to notice and mention it before.

**Comment by c-schuler** [comment]
I purposefully didn't add those as they throw a translation error.

**Pull request merged**
