### PR TITLE
implement MessageEvaluator::stripPHI

### LINKED ISSUE #415: MessageEvaluator::stripPHI is unimplemented
Hi :)

I was going through some of the `todo`s in the codebase and saw that `MessageEvaluator::stripPHI` was not implemented.

[MessageEvaluator.java](https://github.com/DBCG/cql_engine/blob/v1.5.0/engine/src/main/java/org/opencds/cqf/cql/engine/elm/execution/MessageEvaluator.java#L50-L53)
```java
private static Object stripPHI(Object source) {
    // TODO
    return source;
}
```

I have some ideas on how one might implement this functionality but was curious if the maintainers had discussed this topic at all.

### LINKED ISSUE #945: MessageEvaluator::stripPHI is unimplemented

### PR DESCRIPTION
**Pull request by deekim**
resolves cqframework/clinical_quality_language#945

### CODE REVIEW

**Review by JPercival — APPROVED** [review]
LGTM

**Comment by deekim** [comment]
@brynrhodes sorry to bug you.
This fell off my radar, and I was just wondering if you had any additional feedback?

**Comment by deekim** [comment]
@JPercival I think this may have been inadvertently closed when you deleted the `develop` branch?

Any chance we could get this change into the `1.5.2` release? 
We need this change for `HIPAA` compliance reasons 
and were hoping to have to depend on a `SNAPSHOT` version.

**Comment by JPercival** [comment]
@brynrhodes - Bump

**Pull request merged**
