### PR TITLE
CQF1271 fix test cases

### PR DESCRIPTION
**Pull request by leima888**

### CODE REVIEW

**Comment by brynrhodes** [comment]
This has conflicts so I cannot merge it, can you resolve the conflict? Just take the new numbers from the base branch.

**Comment by leima888** [comment]
Resolved all conflicts.

**Comment by brynrhodes** [comment]
From the latest build it looks like passing tests went down on this, can you take a look at that?

**Comment by brynrhodes** [comment]
It's actually impossible to see what really happened on this PR now after that merge, can you take just the changes you made and submit a new PR with them?

**Comment by leima888** [comment]
I have more test cases to fix and will fix any discrepancies as I see them. Are you going to close this PR since you have already merged it to the base?

**Comment by brynrhodes** [comment]
I haven't merged it into the feature-test-cql branch yet, I can't tell what really happened after the conflict resolution, so I'm saying it would be easier to review if you start a new branch from feature-test-cql and just apply your changes to that and submit a new PR for it. If you agree, yes, I'll close this PR.

**Comment by leima888** [comment]
Should I branch or fork? Branch is much easier to handle but am I authorized/supposed to create a branch? Since I've already have a fork of this project it looks like I have to delete the fork in order to create a new one.

**Pull request closed without merging**
