### PR TITLE
Enhancement #122 test suite

### PR DESCRIPTION
**Pull request by c-schuler**
This rather large pull request serves the following purposes:
1. Pull in the Bonnie test suite
    a. Fix any issues with operators
    b. Document and report any discrepancies 
2. Begin implementing a portable test suite
3. DateTime/Time migration from Joda Time to Java 8 Time

For item 1, there are some missing tests:
- The Bonnie tests that check for valid Quantity units are commented out (will include once 1.3 is released)
- Tests that require retrieval of resources or terminology have not been included
- Tests with invalid results due to non-conformance to the CQL specification v1.2.1 have been commented out and will be raised as an issue in the Bonnie repo

For item 2, I decided to scrap the work done by Darren Duncan, which used an XML suite much like the FHIRPath tests. I did away with that work because I really dislike the amount of work it requires from implementers to run it and because it takes far too long to execute (~8 mins). I decided to go with a set of pure CQL libraries that use the Message operator (and several conversion functions) to report whether the test passed or failed. I think this greatly improves the usability of the tests as the implementer merely needs to translate and execute the expressions with basic boilerplate code and the execution time is <1 min.

For item 3, there were so many issues with the DateTime and Time logic that a large refactoring was in store. I decided to migrate to Java 8 Time as part of this refactoring to satisfy another issue (#121). Joda Time recommends this migration and the logic was greatly simplified.

### CODE REVIEW

**Comment by duncand** [comment]
Please don't delete my XML-based portable test suite, rather just add your new one in parallel.

Purely by coincidence, today being a long weekend where I live, I was planning to continue my work on the XML test suite today, which was incomplete, and then that was going to be a priority of mine.

I had already premeditated several improvements to the test suite.

This was starting with a simple change to fix the performance issues you mentioned.  In a nutshell, the overhead of parsing the CQL for each test fully isolated was the problem; so I was going to parse all the tests together at once, with a single Translator call (actually 2), which would make it take almost zero time.

Another change was making it possible to reliably test in a portable way CQL semantics in the generic suite that previously were only possible in the legacy Java, such as testing that uncertainty results are exactly as expected.

I will also be making any improvements for compatibility as the CQL spec and CQL Engine implementation has changed.

You said: "For item 2, I decided to scrap the work done by Darren Duncan, which used an XML suite much like the FHIRPath tests. I did away with that work because I really dislike the amount of work it requires from implementers to run it and because it takes far too long to execute (~8 mins). I decided to go with a set of pure CQL libraries that use the Message operator (and several conversion functions) to report whether the test passed or failed. I think this greatly improves the usability of the tests as the implementer merely needs to translate and execute the expressions with basic boilerplate code and the execution time is <1 min."

With regards to that, pure CQL libraries is exactly how I implemented the portable test suite the first time, and this approach was rejected, saying that the XML-based approach like the FHIRPath tests was the correct way forward, and so I did it that way on my second version and I agree that was a superior approach.  At least considering that at the time CQL itself was not sufficiently computationally complete to properly test corner cases.

Please explain why you think the XML-based approach I used requires too much work from implementers to run it.  Depending on the reasoning, I may be able to fix it easily while I'm making the other improvements.

Regardless of whether your testing solution is actually superior, please leave the XML one alone in the source tree so it is available for now as a parallel option.

This pull request should not be approved until it has been modified to only add the new tests without removing the old ones.

Thank you.

**Comment by duncand** [comment]
On a further note, running the entire portable XML test suite, for the engine proper and not including the FHIRpath tests, took 2m25s, as of its committed state on 2018 March 12, on my machine, which is an iMac dating from 2013.  After my performance fix this should be reduced almost to zero.  If its taking 8 minutes for you, then either you're including the FHIRpath tests, not part of the portable suite, or your hardware is much slower than mine, or the translator/engine itself became a lot slower.  I will re-test the latest shortly.

**Review by brynrhodes — APPROVED** [review]
Reviewed the code with submitter, discussed pros and cons of the approach and I agree with the overall change, but would like to see a mechanism to get to a portable test suite in the future. The FHIRPath one is simple and straightforward, the additional one added directly to the engine that is removed by this pull request is overly complex for what it needs to accomplish.

**Comment by c-schuler** [comment]
@duncand I'd be happy to review a simplified approach to your first attempt at the XML test suite. Feel free to add a PR and request my review. We appreciate your contributions to this project and don't want to discourage future collaboration. Thank you.

**Comment by duncand** [comment]
@c-schuler So let me ask you both this:  One constraint I was under originally when developing the XML test suite for CQL-Engine was to keep the input file format exactly the same as the FHIR one it was based on, as well to a lesser extent to keep the output format the same.  Also my pre-meditated further enhancements would have maintained that constraint but otherwise had a goal of being able to completely handle the legacy Java+CQL suite's features.  However, if that constraint no longer exists and I can evolve it to simply be a good portable test suite, I will be able to achieve something that is both simpler and more powerful.  So do you feel that matching the FHIR format is no longer necessary and I can be better?

**Pull request merged**
