### PR TITLE
Accounting for precision and possible null results for DateTime/Time included in evaluator

### PR DESCRIPTION
**Pull request by c-schuler**
@brynrhodes - Please verify the logic conforms to the spec. I am returning null if the DateTime/Time comparisons return null, but perhaps it should return false?

### CODE REVIEW

**Comment by jeffeastman** [comment]
The spec (p54) says: "Each of these operators [including IncludedIn] returns true if the intervals X and Y are in the given relationship to each other. If either or both arguments are null, the result is null. Otherwise, the result is false.".

**Comment by jeffeastman** [comment]
Turns out I have only the 1.1 spec. Could you email me the 1.2?

In my example, the DateTimes looked to be equal but were actually of different precision. So I still believe that the left argument of IncludedIn should have been null and the result also.

**Comment by c-schuler** [comment]
I sent that.

From your example:
```
X = Interval [ 2017-09-01T00:00:00, 2017-09-01T00:00:00 ]
Y = Interval [ 2017-09-01T00:00:00.000, 2017-12-30T23:59:59.999 ]
```

The call is IncludedIn(X, Y). The arguments X and Y are clearly not null. 
However, the call `LessOrEqualEvaluator.lessOrEqual(Y.start(), X.start())` results in null because of the difference in precision, which is the reason for the NPE you're getting. I believe the result in that case should be false (although I did code it as you suggested).

**Comment by brynrhodes** [comment]
When a date/time comparison involving date/times of varying precision returns null, it means "I don't know", so the interval operators that are performing comparisons should propagate that and return null themselves, but using 3VL semantics. In other words, the following two CQL expressions should give us the same answer:

    IntervalA during IntervalB

    start of IntervalA >= start of IntervalB and end of IntervalA <= end of IntervalB

So I think the way it's coded in this fix is correct, but we should probably reuse the LogicalAnd execution logic.

**Comment by c-schuler** [comment]
Yeah, my bad. I was returning null if either of the comparisons were null, which isn't how the AndEvaluator works. However, like the equivalent expressions you outlined above, if one is false and the other is null, we should return false.

**Pull request merged**
