### PR TITLE
Added R4 and STU3 search params for Patient context 

### PR DESCRIPTION
**Pull request by c-schuler**

### CODE REVIEW

**Review by brynrhodes — CHANGES_REQUESTED** [review]
Looks good, is there an issue this is related to?

**Comment by c-schuler** [comment]
No. This is an enhancement for the R4 and STU3 data providers. I noticed that whenever the patient compartment had multiple inclusion criteria for a resource, the R4 data provider returned null. I fixed that and added this logic to the Stu3 data provider as well. I did not check the other compartments, so we may want to create an issue to ensure those are complete.

**Comment by brynrhodes** [comment]
Well, I'm suggesting that this should have an issue created to track to.

**Comment by c-schuler** [comment]
Understood. Created issue #241 for tracking

**Review by brynrhodes — APPROVED** [review]

**Pull request merged**
