### PR TITLE
Issue #52 - add Engine support for CQL external functions

### PR DESCRIPTION
**Pull request by duncand**
This is an initial working implementation of CQL external functions in the engine.

It was co-developed by Darren and Chris.

### CODE REVIEW

**Comment by duncand** [comment]
Please hold off on merging this.  I discovered it added a bug.  A fix is pending shortly.

**Comment by duncand** [comment]
The current external functions implementation works at the whole engine level, operating by adding extra functions as if they were built-in to the engine and available for all libraries the engine powers.  The Java code instantiating the engine Context object names the Java library defining the external functions, and the CQL libraries themselves don't know anything about that, they only know they can use the extra functions.  Altering this system so the CQL libraries can be aware of multiple external function libraries should be left to another task, and the current work should be merged as is.  Such changes will take their own rounds of planning and deciding what works best.

**Comment by duncand** [comment]
The external function provider itself is not associated with any specific CQL library.  It is only meant to be a resource that one or more CQL libraries can use, same as they use e.g. FHIRHelpers now.  They just happen to not be implemented in CQL but rather in Java.

**Comment by c-schuler** [comment]
As Bryn also stated, I am fine with merging this work as is and creating a new ticket for his suggestion. @duncand I am not sure what you mean by "Altering this system so the CQL libraries can be aware of multiple external function libraries". Why would the CQL need to be aware of multiple external function libraries? It should be as simple as registering external function providers (EFP) using a map with the CQL library id as the key. Then when an external function provider is retrieved, just use the current library stack to retrieve the correct EFP.

**Comment by duncand** [comment]
@c-schuler - On further thought I think I get what is being suggested now.  I will make an alteration to the code so that an external provider library is mapped with a CQL library via the declared name of the latter.  I agree this is a better design.

**Comment by duncand** [comment]
@c-schuler or @brynrhodes - Please review my altered version, and if you accept that, please merge it, thank you.

**Comment by c-schuler** [comment]
Looks good. One thing I would like to see is a more thorough test that tests a possible use case (like libraries that reference a function with the same signature, but have different results).
Something like the following:
```
library CqlExternalFunctionsTest version '3'

include AnotherLibrary version '1' called AnotherLibrary

context Patient

define function MyStringOperation(x String) returns String : external

define CallCurrentStringOperation: 
    MyStringOperation('Testing') // returns TESTING

define CallAnotherStringOperation: 
    AnotherLibrary.MyStringOperation('Testing') // returns testing
```
I am happy to merge as is if you think that request is overkill.

**Comment by duncand** [comment]
I think its hard to know where to draw the line on additional tests.  If we were going to add more than the ones I have then there are probably a bunch of scenarios that should be covered and just doing the one you mention seems arbitrary.  Please merge the existing one but we can make an issue to cover adding more in a broader sense.

**Pull request merged**
